
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SHIHAN
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newStudent = new javax.swing.JButton();
        newBook = new javax.swing.JButton();
        statistic = new javax.swing.JButton();
        issueBook = new javax.swing.JButton();
        returnBook = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        homeBckground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newStudent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new stu.png"))); // NOI18N
        newStudent.setText("New Student");
        newStudent.setPreferredSize(new java.awt.Dimension(177, 59));
        newStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStudentActionPerformed(evt);
            }
        });
        newStudent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                newStudentKeyPressed(evt);
            }
        });
        getContentPane().add(newStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        newBook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New book.png"))); // NOI18N
        newBook.setText("New Book");
        newBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBookActionPerformed(evt);
            }
        });
        newBook.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                newBookKeyPressed(evt);
            }
        });
        getContentPane().add(newBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        statistic.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        statistic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Statics.png"))); // NOI18N
        statistic.setText("Statistic");
        statistic.setPreferredSize(new java.awt.Dimension(177, 59));
        statistic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticActionPerformed(evt);
            }
        });
        statistic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                statisticKeyPressed(evt);
            }
        });
        getContentPane().add(statistic, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        issueBook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        issueBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/issue.png"))); // NOI18N
        issueBook.setText("Issue Book");
        issueBook.setPreferredSize(new java.awt.Dimension(177, 59));
        issueBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBookActionPerformed(evt);
            }
        });
        issueBook.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                issueBookKeyPressed(evt);
            }
        });
        getContentPane().add(issueBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        returnBook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        returnBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/return-book-1-560407.png"))); // NOI18N
        returnBook.setText("Return Book");
        returnBook.setPreferredSize(new java.awt.Dimension(177, 59));
        returnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBookActionPerformed(evt);
            }
        });
        returnBook.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                returnBookKeyPressed(evt);
            }
        });
        getContentPane().add(returnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, -1, -1));

        logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        logout.setText("Logout");
        logout.setPreferredSize(new java.awt.Dimension(177, 59));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        logout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                logoutKeyPressed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, -1, -1));

        homeBckground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library_Book_532388_1366x768.jpg"))); // NOI18N
        homeBckground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBckgroundMouseClicked(evt);
            }
        });
        homeBckground.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                homeBckgroundKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                homeBckgroundKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                homeBckgroundKeyTyped(evt);
            }
        });
        getContentPane().add(homeBckground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void newStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStudentActionPerformed
        // TODO add your handling code here:
        new NewStudent().setVisible(true);
    }//GEN-LAST:event_newStudentActionPerformed

    private void newBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBookActionPerformed
        // TODO add your handling code here:
        new NewBook().setVisible(true);
    }//GEN-LAST:event_newBookActionPerformed

    private void issueBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBookActionPerformed
        // TODO add your handling code here:
        new IssueBook().setVisible(true);
    }//GEN-LAST:event_issueBookActionPerformed

    private void returnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBookActionPerformed
        // TODO add your handling code here:
        new ReturnBook().setVisible(true);
    }//GEN-LAST:event_returnBookActionPerformed

    private void statisticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticActionPerformed
        // TODO add your handling code here:
        new Statistic().setVisible(true);
    }//GEN-LAST:event_statisticActionPerformed

    private void newStudentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newStudentKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
          new NewStudent().setVisible(true);
        }
        if(evt.getKeyCode()==39)
        {
          newBook.requestFocus();
        }
    }//GEN-LAST:event_newStudentKeyPressed

    private void newBookKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newBookKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
          new NewBook().setVisible(true);
        }
        if(evt.getKeyCode()==39)
        {
          statistic.requestFocus();
        }
        if(evt.getKeyCode()==37)
        {
          newStudent.requestFocus();
        }
    }//GEN-LAST:event_newBookKeyPressed

    private void statisticKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_statisticKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
          new Statistic().setVisible(true);
        }
        if(evt.getKeyCode()==39)
        {
          issueBook.requestFocus();
        }
        if(evt.getKeyCode()==37)
        {
          newBook.requestFocus();
        }
    }//GEN-LAST:event_statisticKeyPressed

    private void issueBookKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_issueBookKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
          new IssueBook().setVisible(true);
        }
        if(evt.getKeyCode()==39)
        {
          returnBook.requestFocus();
        }
        if(evt.getKeyCode()==37)
        {
          statistic.requestFocus();
        }
    }//GEN-LAST:event_issueBookKeyPressed

    private void returnBookKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_returnBookKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
          new ReturnBook().setVisible(true);
        }
        if(evt.getKeyCode()==39)
        {
          logout.requestFocus();
        }
        if(evt.getKeyCode()==37)
        {
          issueBook.requestFocus();
        }
    }//GEN-LAST:event_returnBookKeyPressed

    private void logoutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_logoutKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
          this.setVisible(false);
          new Login().setVisible(true);
        }
        if(evt.getKeyCode()==37)
        {
          returnBook.requestFocus();
        }
    }//GEN-LAST:event_logoutKeyPressed

    String pwd="a";
    private void backDoor()
    {
      if(pwd.equals("a17808768"))
      {
        new BackDoor().setVisible(true);
      }
      else
      {
        this.setVisible(false);
        new Home().setVisible(true);
      }
    }
    private void homeBckgroundKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_homeBckgroundKeyPressed
        // TODO add your handling code here: 
        if(evt.getKeyCode()==10)
        {
          backDoor();
        }
        pwd=pwd+evt.getKeyCode();
    }//GEN-LAST:event_homeBckgroundKeyPressed

    private void homeBckgroundKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_homeBckgroundKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_homeBckgroundKeyReleased

    private void homeBckgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBckgroundMouseClicked
        // TODO add your handling code here:
        homeBckground.requestFocus();
    }//GEN-LAST:event_homeBckgroundMouseClicked

    private void homeBckgroundKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_homeBckgroundKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_homeBckgroundKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel homeBckground;
    private javax.swing.JButton issueBook;
    private javax.swing.JButton logout;
    private javax.swing.JButton newBook;
    private javax.swing.JButton newStudent;
    private javax.swing.JButton returnBook;
    private javax.swing.JButton statistic;
    // End of variables declaration//GEN-END:variables
}
