
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import project.DatabaseConnection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SHIHAN
 */
public class IssueBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    public IssueBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bookID = new javax.swing.JTextField();
        studentID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        issueDate = new com.toedter.calendar.JDateChooser();
        dueDate = new com.toedter.calendar.JDateChooser();
        close = new javax.swing.JButton();
        issue = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 125));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Book Id:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        bookID.setBackground(new java.awt.Color(255, 255, 204));
        bookID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bookID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bookIDFocusGained(evt);
            }
        });
        bookID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bookIDKeyPressed(evt);
            }
        });
        getContentPane().add(bookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 257, -1));

        studentID.setBackground(new java.awt.Color(255, 255, 204));
        studentID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        studentID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                studentIDKeyPressed(evt);
            }
        });
        getContentPane().add(studentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 257, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Student ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Issue Date:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Due Date:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        issueDate.setBackground(new java.awt.Color(255, 255, 204));
        issueDate.setDateFormatString("yyy--MM-d");
        issueDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        issueDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                issueDateKeyPressed(evt);
            }
        });
        getContentPane().add(issueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 257, 23));

        dueDate.setBackground(new java.awt.Color(255, 255, 204));
        dueDate.setDateFormatString("yyy--MM-d");
        dueDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dueDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dueDateKeyPressed(evt);
            }
        });
        getContentPane().add(dueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 257, 23));

        close.setBackground(new java.awt.Color(255, 255, 204));
        close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red-x-mark-transparent-background-3.png"))); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        close.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                closeKeyPressed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 100, 31));

        issue.setBackground(new java.awt.Color(255, 255, 204));
        issue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        issue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/issue book.png"))); // NOI18N
        issue.setText("Issue");
        issue.setPreferredSize(new java.awt.Dimension(93, 29));
        issue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueActionPerformed(evt);
            }
        });
        issue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                issueKeyPressed(evt);
            }
        });
        getContentPane().add(issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 100, 31));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/123456.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    
    private void issueBookIssueButton()
    {
       String bID=bookID.getText();
        String sID=studentID.getText();
        
        SimpleDateFormat sdf=new SimpleDateFormat("yyy-MM-d");
        String iissueDate=sdf.format(issueDate.getDate());
        String ddueDate=sdf.format(dueDate.getDate());
        String returnBook="no";
        

        String query="insert into issueBook(id,studentID,issueDate,dueDate,returnBook)values(?,?,?,?,?);";
        if(!("".equals(bookID.getText())))
        {
            try(Connection con=DatabaseConnection.connection())
            {
              Statement st=con.createStatement();
              ResultSet rs=st.executeQuery("select id from newBook where id="+bID+";");
              if(rs.next())
              {
                ResultSet rs1=st.executeQuery("select studentID from newStudent where studentID="+sID+";");
                if(rs1.next())
                {
                   PreparedStatement pst=con.prepareStatement(query);
                   pst.setString(1,bID);
                   pst.setString(2,sID);
                   pst.setString(3,iissueDate);
                   pst.setString(4,ddueDate);
                   pst.setString(5,returnBook);
                   boolean status=pst.execute();

                if(!status)
                {
                    JOptionPane.showMessageDialog(null,"Book is given to "+sID);
                    this.setVisible(false);
                    new IssueBook().setVisible(true);
                } 
                }
                else
                {
                  JOptionPane.showMessageDialog(null,"STUDENT ID is invalid!");
                }
              }
              else
              {
                JOptionPane.showMessageDialog(null,"BOOK ID is invalid!");
              }
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
        } 
    }
    private void issueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueActionPerformed
        // TODO add your handling code here:
        issueBookIssueButton();
    }//GEN-LAST:event_issueActionPerformed

    private void bookIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bookIDKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==10 || evt.getKeyCode()==40)
        {
          studentID.requestFocus();
        }
        
    }//GEN-LAST:event_bookIDKeyPressed

    private void studentIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentIDKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==10 || evt.getKeyCode()==40)
        {
          issueDate.requestFocus();
        }
        if(evt.getKeyCode()==38)
        {
          bookID.requestFocus();
        }
    }//GEN-LAST:event_studentIDKeyPressed

    private void issueDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_issueDateKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==10 || evt.getKeyCode()==40)
        {
          dueDate.requestFocus();
        }
        if(evt.getKeyCode()==38)
        {
          studentID.requestFocus();
        }
    }//GEN-LAST:event_issueDateKeyPressed

    private void dueDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dueDateKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==10 || evt.getKeyCode()==40)
        {
          issue.requestFocus();
        }
        if(evt.getKeyCode()==38)
        {
          issueDate.requestFocus();
        }
    }//GEN-LAST:event_dueDateKeyPressed

    private void issueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_issueKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==10)
        {
          issueBookIssueButton();
        }
        if(evt.getKeyCode()==38)
        {
          dueDate.requestFocus();
        }
        if(evt.getKeyCode()==39)
        {
          close.requestFocus();
        }
    }//GEN-LAST:event_issueKeyPressed

    private void closeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_closeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
          this.setVisible(false);
        }
        if(evt.getKeyCode()==38)
        {
          dueDate.requestFocus();
        }
        if(evt.getKeyCode()==37)
        {
          issue.requestFocus();
        }
    }//GEN-LAST:event_closeKeyPressed

    private void bookIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookIDFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_bookIDFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookID;
    private javax.swing.JButton close;
    private com.toedter.calendar.JDateChooser dueDate;
    private javax.swing.JButton issue;
    private com.toedter.calendar.JDateChooser issueDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField studentID;
    // End of variables declaration//GEN-END:variables
}
