
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import project.DatabaseConnection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SHIHAN
 */
public class NewBook extends javax.swing.JFrame {

    /**
     * Creates new form NewBook
     */
    public NewBook() {
        initComponents();
        errorMsg.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        errorMsg = new javax.swing.JLabel();
        autoGenerate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bookID = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        publisher = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        close = new javax.swing.JButton();
        price = new javax.swing.JTextField();
        publishedYear = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 125));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        errorMsg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        errorMsg.setForeground(new java.awt.Color(255, 0, 0));
        errorMsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bad face_1.png"))); // NOI18N
        getContentPane().add(errorMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        autoGenerate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        autoGenerate.setText("Auto generate ?");
        autoGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoGenerateActionPerformed(evt);
            }
        });
        getContentPane().add(autoGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Book Id:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Publisher:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Price:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Published Year:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        bookID.setBackground(new java.awt.Color(255, 255, 204));
        bookID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bookID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bookIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bookIDFocusLost(evt);
            }
        });
        bookID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bookIDKeyPressed(evt);
            }
        });
        getContentPane().add(bookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 257, -1));

        name.setBackground(new java.awt.Color(255, 255, 204));
        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameKeyPressed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 257, -1));

        publisher.setBackground(new java.awt.Color(255, 255, 204));
        publisher.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        publisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publisherActionPerformed(evt);
            }
        });
        publisher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                publisherKeyPressed(evt);
            }
        });
        getContentPane().add(publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 257, -1));

        save.setBackground(new java.awt.Color(255, 255, 204));
        save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save-icon--1.png"))); // NOI18N
        save.setText("Save");
        save.setPreferredSize(new java.awt.Dimension(93, 29));
        save.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                saveFocusLost(evt);
            }
        });
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        save.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                saveKeyPressed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, 31));

        close.setBackground(new java.awt.Color(255, 255, 204));
        close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red-x-mark-transparent-background-3.png"))); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        close.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                closeKeyPressed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, 31));

        price.setBackground(new java.awt.Color(255, 255, 204));
        price.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                priceKeyPressed(evt);
            }
        });
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 257, -1));

        publishedYear.setBackground(new java.awt.Color(255, 255, 204));
        publishedYear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        publishedYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publishedYearActionPerformed(evt);
            }
        });
        publishedYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                publishedYearKeyPressed(evt);
            }
        });
        getContentPane().add(publishedYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 257, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/123456.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void publisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_publisherActionPerformed

    private void newBookSaveButton()
    {
       String bID=bookID.getText();
        String bName=name.getText();
        String bPublisher=publisher.getText();
        String bPrice=price.getText();
        String bPublisherYear=publishedYear.getText();

        String query="insert into newBook(id,name,publisher,price,publishedYear)values(?,?,?,?,?);";
        if(!("".equals(publishedYear.getText())) && !("".equals(price.getText())) && !("".equals(publisher.getText())) && !("".equals(name.getText())) && !("".equals(bookID.getText())))
        {
            try(Connection con=DatabaseConnection.connection())
            {
                PreparedStatement pst=con.prepareStatement(query);
                pst.setString(1,bID);
                pst.setString(2,bName);
                pst.setString(3,bPublisher);
                pst.setString(4,bPrice);
                pst.setString(5,bPublisherYear);
                boolean status=pst.execute();

                if(!status)
                {
                    JOptionPane.showMessageDialog(null,"Book is added!");
                    this.setVisible(false);
                    new NewBook().setVisible(true);
                }
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
        }
        else
        {
          errorMsg.setText("Every field is mandatory!!");
          errorMsg.setVisible(true);
        }
    }
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        newBookSaveButton();
    }//GEN-LAST:event_saveActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void publishedYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publishedYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_publishedYearActionPerformed

    private void bookIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bookIDKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==40 || evt.getKeyCode()==10)
        {
          name.requestFocus();
        }
    }//GEN-LAST:event_bookIDKeyPressed

    private void nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==10 || evt.getKeyCode()==40)
        {
          publisher.requestFocus();
        }
        if(evt.getKeyCode()==38)
        {
          bookID.requestFocus();
        }
    }//GEN-LAST:event_nameKeyPressed

    private void publisherKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_publisherKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==10 || evt.getKeyCode()==40)
        {
          price.requestFocus();
        }
        if(evt.getKeyCode()==38)
        {
          name.requestFocus();
        }
    }//GEN-LAST:event_publisherKeyPressed

    private void priceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==10 || evt.getKeyCode()==40)
        {
          publishedYear.requestFocus();
        }
        if(evt.getKeyCode()==38)
        {
          publisher.requestFocus();
        }
    }//GEN-LAST:event_priceKeyPressed

    private void publishedYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_publishedYearKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==10 || evt.getKeyCode()==40)
        {
          save.requestFocus();
        }
        if(evt.getKeyCode()==38)
        {
          price.requestFocus();
        }
    }//GEN-LAST:event_publishedYearKeyPressed

    private void saveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saveKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==10)
        {
          newBookSaveButton();
        }
        if(evt.getKeyCode()==38)
        {
          publishedYear.requestFocus();
        }
        if(evt.getKeyCode()==39)
        {
          close.requestFocus();
        }
    }//GEN-LAST:event_saveKeyPressed

    private void closeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_closeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==38)
        {
          publishedYear.requestFocus();
        }
        if(evt.getKeyCode()==10)
        {
          this.setVisible(false);
        }
        if(evt.getKeyCode()==37)
        {
          save.requestFocus();
        }
    }//GEN-LAST:event_closeKeyPressed

    private void autoGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoGenerateActionPerformed
        // TODO add your handling code here:
        errorMsg.setVisible(false);
        bookID.setBackground(new Color(255,255,204));
        bookID.setText("");
        bookID.setEditable(false);

        Connection con=DatabaseConnection.connection();
        String sID=bookID.getText();
        int greaterNumber=0;

        Statement st;
        try
        {
            st = con.createStatement();
            ResultSet rs=st.executeQuery("select id from newbook"+";");
            while(rs.next())
            {
                for(;(greaterNumber <= rs.getInt(1));)
                {
                    greaterNumber=greaterNumber+1;
                }
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(NewStudent.class.getName()).log(Level.SEVERE, null, ex);
        }

        String s=Integer.toString(greaterNumber);
        bookID.setText(s);

    }//GEN-LAST:event_autoGenerateActionPerformed

    private void saveFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_saveFocusLost
        // TODO add your handling code here:
        errorMsg.setVisible(false);
    }//GEN-LAST:event_saveFocusLost

    private void bookIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookIDFocusLost
        // TODO add your handling code here:
        Connection con=DatabaseConnection.connection();
        String sID=bookID.getText();
        try 
        {
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select id from newbook where id="+"\""+sID+"\""+";");
            
            if(rs.next())
            {
               if(sID.equals(rs.getString(1)))
               {
                   errorMsg.setVisible(true);
                   errorMsg.setText("The student id is already taken!");
                   bookID.setBackground(new Color(255,51,51));
               }
            }
            
        } 
        catch (SQLException ex) {
            Logger.getLogger(NewStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bookIDFocusLost

    private void bookIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookIDFocusGained
        // TODO add your handling code here:
        errorMsg.setVisible(false);
        bookID.setBackground(new Color(255,255,204));
    }//GEN-LAST:event_bookIDFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton autoGenerate;
    private javax.swing.JTextField bookID;
    private javax.swing.JButton close;
    private javax.swing.JLabel errorMsg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField name;
    private javax.swing.JTextField price;
    private javax.swing.JTextField publishedYear;
    private javax.swing.JTextField publisher;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
