
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import project.DatabaseConnection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SHIHAN
 */
public class NewStudent extends javax.swing.JFrame {
    
    public NewStudent() {
        initComponents();
         errorMsg.setVisible(false);
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        autoGenerate = new javax.swing.JButton();
        errorMsg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        studentID = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        fathersName = new javax.swing.JTextField();
        courseName = new javax.swing.JComboBox<>();
        branchName = new javax.swing.JComboBox<>();
        save = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 125));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        autoGenerate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        autoGenerate.setText("Auto generate ?");
        autoGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoGenerateActionPerformed(evt);
            }
        });
        getContentPane().add(autoGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, -1, -1));

        errorMsg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        errorMsg.setForeground(new java.awt.Color(255, 0, 0));
        errorMsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bad face_1.png"))); // NOI18N
        getContentPane().add(errorMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Student Id:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Father's Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Course Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Branch Name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        studentID.setBackground(new java.awt.Color(255, 255, 204));
        studentID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        studentID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                studentIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                studentIDFocusLost(evt);
            }
        });
        studentID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                studentIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                studentIDKeyReleased(evt);
            }
        });
        getContentPane().add(studentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 257, -1));

        name.setBackground(new java.awt.Color(255, 255, 204));
        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameKeyPressed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 257, -1));

        fathersName.setBackground(new java.awt.Color(255, 255, 204));
        fathersName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fathersName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fathersNameActionPerformed(evt);
            }
        });
        fathersName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fathersNameKeyPressed(evt);
            }
        });
        getContentPane().add(fathersName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 257, -1));

        courseName.setBackground(new java.awt.Color(255, 255, 204));
        courseName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        courseName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B.Tech" }));
        courseName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                courseNameKeyPressed(evt);
            }
        });
        getContentPane().add(courseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 257, -1));

        branchName.setBackground(new java.awt.Color(255, 255, 204));
        branchName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        branchName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSE", "Graphic", "Web", "Network" }));
        branchName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                branchNameKeyPressed(evt);
            }
        });
        getContentPane().add(branchName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 257, -1));

        save.setBackground(new java.awt.Color(255, 255, 204));
        save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save-icon--1.png"))); // NOI18N
        save.setText("Save");
        save.setPreferredSize(new java.awt.Dimension(93, 29));
        save.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                saveFocusLost(evt);
            }
        });
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        save.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                saveKeyPressed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, 31));

        close.setBackground(new java.awt.Color(255, 255, 204));
        close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red-x-mark-transparent-background-3.png"))); // NOI18N
        close.setText("Close");
        close.setPreferredSize(new java.awt.Dimension(93, 29));
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        close.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                closeKeyPressed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, 31));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/123456.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fathersNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fathersNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fathersNameActionPerformed

    private void newStudenttSaveButton()
    {
        String sID=studentID.getText();
        String sName=name.getText();
        String sFathersName=fathersName.getText();
        String sCourseName=(String)courseName.getSelectedItem();
        String sBranchName=(String)branchName.getSelectedItem();
        
      String query="insert into newStudent(studentID,name,fathersName,courseName,branchName)values(?,?,?,?,?);";
      if((studentID.getText().matches("[0-9]+")) && !("".equals(name.getText())) && !("".equals(fathersName.getText())))
     {
        try(Connection con=DatabaseConnection.connection())
        {
          PreparedStatement pst=con.prepareStatement(query); 
          pst.setString(1, sID);
          pst.setString(2,sName);
          pst.setString(3,sFathersName);
          pst.setString(4,sCourseName);
          pst.setString(5,sBranchName);
          boolean status=pst.execute();
          
          if(!status)
          {
            JOptionPane.showMessageDialog(null,sName+" is added!");
            this.setVisible(false);
            new NewStudent().setVisible(true);
          }
        }
        catch(Exception e)
        {
          e.printStackTrace();      
        }
      }
    }
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        newStudenttSaveButton();
     if(("".equals(studentID.getText())) || ("".equals(name.getText())) || ("".equals(fathersName.getText())))
     {
        errorMsg.setText("Every fields mandatory!!");
        errorMsg.setVisible(true);
     }
    }//GEN-LAST:event_saveActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void studentIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentIDKeyPressed
        // TODO add your handling code here:
           
        if( evt.getKeyCode()==40 || evt.getKeyCode()==10)
        {
          name.requestFocus();
        }
        
    }//GEN-LAST:event_studentIDKeyPressed

    private void nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10 || evt.getKeyCode()==40)
        {
          fathersName.requestFocus();
        }
        if(evt.getKeyCode()==38)
        {
          studentID.requestFocus();
        }
    }//GEN-LAST:event_nameKeyPressed

    private void fathersNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fathersNameKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==10 || evt.getKeyCode()==40)
        {
          courseName.requestFocus();
        }
        if(evt.getKeyCode()==38)
        {
          name.requestFocus();
        }
    }//GEN-LAST:event_fathersNameKeyPressed

    private void courseNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_courseNameKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==10)
        {
          branchName.requestFocus();
        }
    }//GEN-LAST:event_courseNameKeyPressed

    private void branchNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_branchNameKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==10)
        {
          save.requestFocus();
        }
    }//GEN-LAST:event_branchNameKeyPressed

    private void saveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saveKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==10)
        {
          newStudenttSaveButton();
        }
        if(evt.getKeyCode()==38)
        {
          branchName.requestFocus();
        }
        if(evt.getKeyCode()==39)
        {
          close.requestFocus();
        }
    }//GEN-LAST:event_saveKeyPressed

    private void closeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_closeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==37)
        {
          save.requestFocus();
        }
        if(evt.getKeyCode()==38)
        {
          branchName.requestFocus();
        }
        if(evt.getKeyCode()==10)
        {
          this.setVisible(false);
        }
    }//GEN-LAST:event_closeKeyPressed

    private void studentIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentIDKeyReleased
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_studentIDKeyReleased

    private void isIDexist()
    {
        Connection con=DatabaseConnection.connection();
        String sID=studentID.getText();
        try 
        {
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select studentID from newStudent where studentID="+"\""+sID+"\""+";");
            
            if(rs.next())
            {
               if(sID.equals(rs.getString(1)))
               {
                   errorMsg.setVisible(true);
                   errorMsg.setText("The student id is already taken!");
                   studentID.setBackground(new Color(255,51,51));
               }
            }
            
        } 
        catch (SQLException ex) {
            Logger.getLogger(NewStudent.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }
    private void studentIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentIDFocusLost
        // TODO add your handling code here:
        isIDexist();
       
    }//GEN-LAST:event_studentIDFocusLost

    private void studentIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentIDFocusGained
        // TODO add your handling code here:
        errorMsg.setVisible(false);
        studentID.setBackground(new Color(255,255,204));
    }//GEN-LAST:event_studentIDFocusGained

    private void autoGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoGenerateActionPerformed
        // TODO add your handling code here:
        errorMsg.setVisible(false);
        studentID.setBackground(new Color(255,255,204));
        studentID.setText("");
        studentID.setEditable(false);
        
        Connection con=DatabaseConnection.connection();
        String sID=studentID.getText();
        int greaterNumber=0;
       
        Statement st;
        try 
        {
            st = con.createStatement();
            ResultSet rs=st.executeQuery("select studentID from newStudent"+";");
            while(rs.next())
            {
              for(;(greaterNumber <= rs.getInt(1));)
              {
                 greaterNumber=greaterNumber+1;
              }
            }
        } 
        catch (SQLException ex) {
            Logger.getLogger(NewStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String s=Integer.toString(greaterNumber);
        studentID.setText(s);
       
    }//GEN-LAST:event_autoGenerateActionPerformed

    private void saveFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_saveFocusLost
        // TODO add your handling code here:
        errorMsg.setVisible(false);
    }//GEN-LAST:event_saveFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton autoGenerate;
    private javax.swing.JComboBox<String> branchName;
    private javax.swing.JButton close;
    private javax.swing.JComboBox<String> courseName;
    private javax.swing.JLabel errorMsg;
    private javax.swing.JTextField fathersName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField name;
    private javax.swing.JButton save;
    private javax.swing.JTextField studentID;
    // End of variables declaration//GEN-END:variables
}
