
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import project.DatabaseConnection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SHIHAN
 */
public class ReturnBook extends javax.swing.JFrame {
   Connection con=null;
    /**
     * Creates new form ReturnBook
     */
    public ReturnBook() {
        initComponents();
        con=DatabaseConnection.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bookID = new javax.swing.JTextField();
        studentID = new javax.swing.JTextField();
        rreturn = new javax.swing.JButton();
        close = new javax.swing.JButton();
        issueDate = new javax.swing.JTextField();
        dueDate = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 125));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Book Id:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Student ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Issue Date:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Due Date:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        bookID.setBackground(new java.awt.Color(255, 255, 204));
        bookID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bookID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bookIDKeyPressed(evt);
            }
        });
        getContentPane().add(bookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 257, -1));

        studentID.setBackground(new java.awt.Color(255, 255, 204));
        studentID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        studentID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                studentIDKeyPressed(evt);
            }
        });
        getContentPane().add(studentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 257, -1));

        rreturn.setBackground(new java.awt.Color(255, 255, 204));
        rreturn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rreturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/return book png.png"))); // NOI18N
        rreturn.setText("Return");
        rreturn.setPreferredSize(new java.awt.Dimension(93, 29));
        rreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rreturnActionPerformed(evt);
            }
        });
        getContentPane().add(rreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 110, 31));

        close.setBackground(new java.awt.Color(255, 255, 204));
        close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red-x-mark-transparent-background-3.png"))); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 110, 31));

        issueDate.setBackground(new java.awt.Color(255, 255, 204));
        issueDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        issueDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                issueDateKeyPressed(evt);
            }
        });
        getContentPane().add(issueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 257, -1));

        dueDate.setBackground(new java.awt.Color(255, 255, 204));
        dueDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dueDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dueDateKeyPressed(evt);
            }
        });
        getContentPane().add(dueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 257, -1));

        search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/123456.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rreturnActionPerformed
        // TODO add your handling code here:
        String bID=bookID.getText();
        String sID=studentID.getText();
        
       try {
           Statement st=con.createStatement();
           st.executeUpdate("update issueBook set returnBook=\"yes\" where id="+"\""+bID+"\""+"and studentID="+"\""+sID+"\""+";");
           JOptionPane.showMessageDialog(null,"Book successfully returned!");
           this.setVisible(false);
           new ReturnBook().setVisible(true);
       } catch (SQLException ex) {
           Logger.getLogger(ReturnBook.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_rreturnActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    
    private boolean returnBookSearchButton()
    {
        String bID=bookID.getText();
        String sID=studentID.getText();
        boolean b=false;
       try {
           Statement st=con.createStatement();
           ResultSet rs=st.executeQuery("select * from issueBook where id="+"\""+bID+"\""+" and studentID="+"\""+sID+"\""+";");
          
           if(rs.next())
           {
             issueDate.setText(rs.getString(3));
             dueDate.setText(rs.getString(4));
             issueDate.setEditable(false);
             dueDate.setEditable(false);
             bookID.setEditable(false);
             studentID.setEditable(false);
             b=true;
           }
           else
           {
             JOptionPane.showMessageDialog(null,"The book is not issued to this student!");
           }
       } catch (SQLException ex) {
           Logger.getLogger(ReturnBook.class.getName()).log(Level.SEVERE, null, ex);
       }
       return b;
    }
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        returnBookSearchButton();
    }//GEN-LAST:event_searchActionPerformed

    private void bookIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bookIDKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==10 || evt.getKeyCode()==40)
        {
          studentID.requestFocus();
        }
        
    }//GEN-LAST:event_bookIDKeyPressed

    private void studentIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentIDKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==10 || evt.getKeyCode()==39)
        {
          search.requestFocus();
        }
        if(evt.getKeyCode()==38)
        {
          bookID.requestFocus();
        }
        
    }//GEN-LAST:event_studentIDKeyPressed

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==10)
        {
          boolean b=returnBookSearchButton();
          if(b)
          {
            rreturn.requestFocus();
          }
          else
          {
            close.requestFocus();
          }
        }
         if(evt.getKeyCode()==40)
        {
          close.requestFocus();
        }
    }//GEN-LAST:event_searchKeyPressed

    private void issueDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_issueDateKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==10 || evt.getKeyCode()==40)
        {
          dueDate.requestFocus();
        }
        if(evt.getKeyCode()==38)
        {
          studentID.requestFocus();
        }
    }//GEN-LAST:event_issueDateKeyPressed

    private void dueDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dueDateKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==10 || evt.getKeyCode()==40)
        {
          rreturn.requestFocus();
        }
        if(evt.getKeyCode()==38)
        {
          issueDate.requestFocus();
        }
    }//GEN-LAST:event_dueDateKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookID;
    private javax.swing.JButton close;
    private javax.swing.JTextField dueDate;
    private javax.swing.JTextField issueDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton rreturn;
    private javax.swing.JButton search;
    private javax.swing.JTextField studentID;
    // End of variables declaration//GEN-END:variables
}
