
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import project.DatabaseConnection;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SHIHAN
 */
public class SignUp extends javax.swing.JFrame {
    Connection con=null;
    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        errorMsg.setVisible(false);
        happyMsg.setVisible(false);
        ok.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ok = new javax.swing.JButton();
        happyMsg = new javax.swing.JLabel();
        errorMsg = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        securityQuestion = new javax.swing.JComboBox<>();
        answer = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        signUp = new javax.swing.JButton();
        login = new javax.swing.JButton();
        fogotPassword = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(360, 173));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ok.setBackground(new java.awt.Color(0, 102, 0));
        ok.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        ok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                okKeyPressed(evt);
            }
        });
        getContentPane().add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 60, 30));

        happyMsg.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        happyMsg.setForeground(new java.awt.Color(0, 102, 0));
        happyMsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/happ.gif"))); // NOI18N
        getContentPane().add(happyMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 370, 30));

        errorMsg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        errorMsg.setForeground(new java.awt.Color(255, 0, 0));
        errorMsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bad face_1.png"))); // NOI18N
        getContentPane().add(errorMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        close.setBackground(new java.awt.Color(255, 255, 204));
        close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red-x-mark-transparent-background-3.png"))); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        close.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                closeKeyPressed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Name:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Email:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Password:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Security Question:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Answer:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Address:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        name.setBackground(new java.awt.Color(255, 255, 204));
        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameKeyPressed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 390, 30));

        email.setBackground(new java.awt.Color(255, 255, 204));
        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailKeyPressed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 390, 30));

        password.setBackground(new java.awt.Color(255, 255, 204));
        password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 390, 30));

        securityQuestion.setBackground(new java.awt.Color(255, 255, 204));
        securityQuestion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        securityQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is the name of your first pet?", "What was your first car?", "What elementary school did you attend?", "What is the name of the town where you were born?" }));
        securityQuestion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                securityQuestionKeyPressed(evt);
            }
        });
        getContentPane().add(securityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 390, 30));

        answer.setBackground(new java.awt.Color(255, 255, 204));
        answer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerActionPerformed(evt);
            }
        });
        answer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                answerKeyPressed(evt);
            }
        });
        getContentPane().add(answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 390, 30));

        address.setBackground(new java.awt.Color(255, 255, 204));
        address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addressKeyPressed(evt);
            }
        });
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 390, 30));

        signUp.setBackground(new java.awt.Color(255, 255, 204));
        signUp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/signup.png"))); // NOI18N
        signUp.setText("SignUp");
        signUp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                signUpFocusLost(evt);
            }
        });
        signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpActionPerformed(evt);
            }
        });
        signUp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                signUpKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                signUpKeyReleased(evt);
            }
        });
        getContentPane().add(signUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        login.setBackground(new java.awt.Color(255, 255, 204));
        login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login.setIcon(new javax.swing.ImageIcon("E:\\programmin\\jarva\\systems\\library\\Icon 1\\login.png")); // NOI18N
        login.setText("Login");
        login.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginFocusLost(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginKeyPressed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));

        fogotPassword.setBackground(new java.awt.Color(255, 255, 204));
        fogotPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fogotPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fogotpw.png"))); // NOI18N
        fogotPassword.setText("Fogot password?");
        fogotPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fogotPasswordFocusLost(evt);
            }
        });
        fogotPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fogotPasswordActionPerformed(evt);
            }
        });
        fogotPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fogotPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(fogotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 180, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/123456.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void signUpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signUpFocusLost
        // TODO add your handling code here:
        errorMsg.setVisible(false);
    }//GEN-LAST:event_signUpFocusLost

    
    private void signUpButton()
    {
       String uName=name.getText();
       String uEmail=email.getText();
        String uPassword=password.getText();
        String uSecurityQuestion=(String)securityQuestion.getSelectedItem();
        String uAnswer=answer.getText();
        String uAddress=address.getText();
       
        if(uName.isEmpty()||uEmail.isEmpty()||uPassword.isEmpty()||uSecurityQuestion.isEmpty()||uAnswer.isEmpty()||uAddress.isEmpty())
        {
          errorMsg.setText("Every feilds are mandetory!");
          errorMsg.setVisible(true);
        }
        else if(!(uName.isEmpty()||uEmail.isEmpty()||uPassword.isEmpty()||uSecurityQuestion.isEmpty()||uAnswer.isEmpty()||uAddress.isEmpty()) & !(uEmail.matches("[a-zA-Z0-9][a-zA-Z0-9_.]*@[A-Za-z0-9]+([.][a-zA-Z]+)+")))
        {
            /*do nothing(prevent update without validating email)-->errors are display on GUI component by using
            email events*/
        }
        else
        {
            String query="insert into SignUp(name,Email,Password,SecurityQuestion,Answer,Address,Approve)values(?,?,?,?,?,?,?);";
           
               try(Connection con=DatabaseConnection.connection())
               {
                    PreparedStatement pst=con.prepareStatement(query); 
                    pst.setString(1, uName);
                    pst.setString(2,uEmail);
                    pst.setString(3,uPassword);
                    pst.setString(4,uSecurityQuestion);
                    pst.setString(5,uAnswer);
                    pst.setString(6,uAddress);
                    pst.setString(7,"no");
                    boolean status=pst.execute();
          
                    if(!status)
                    {
                        happyMsg.setText("You have to wait until approved by Admin!");
                        happyMsg.setVisible(true);
                        ok.setVisible(true);
                        ok.requestFocus();
                        name.setText("");
                        email.setText("");
                        password.setText("");
                        answer.setText("");
                        address.setText("");
                        //JOptionPane.showMessageDialog(null,uName+" is added!");
                    }
                }
                catch(Exception e)
                {
                    e.printStackTrace();      
                }
        }  
    }
    
    private void signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpActionPerformed
        // TODO add your handling code here:
           signUpButton();    
    }//GEN-LAST:event_signUpActionPerformed

    private void signUpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signUpKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==39)
        {
            login.requestFocus();
        }
        if(evt.getKeyCode()==38)
        {
            address.requestFocus();
        }
        if(evt.getKeyCode()==10)
        {
            signUpButton();
        }
    }//GEN-LAST:event_signUpKeyPressed

    private void loginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFocusLost
        // TODO add your handling code here:
        errorMsg.setVisible(false);
    }//GEN-LAST:event_loginFocusLost

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
    }//GEN-LAST:event_loginActionPerformed

    private void loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==38)
        {
            address.requestFocus();
        }
        if(evt.getKeyCode()==39)
        {
            fogotPassword.requestFocus();
        }
        if(evt.getKeyCode()==10)
        {
           this.setVisible(false);
        }
        if(evt.getKeyCode()==37)
        {
            signUp.requestFocus();
        }
    }//GEN-LAST:event_loginKeyPressed

    private void fogotPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fogotPasswordFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_fogotPasswordFocusLost

    private void fogotPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fogotPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fogotPasswordActionPerformed

    private void fogotPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fogotPasswordKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_fogotPasswordKeyPressed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10 || evt.getKeyCode()==40)
        {
          email.requestFocus();
        }
    }//GEN-LAST:event_nameKeyPressed

    private void emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10 || evt.getKeyCode()==40)
        {
          password.requestFocus();
        }
        if(evt.getKeyCode()==38)
        {
          name.requestFocus();
        }
    }//GEN-LAST:event_emailKeyPressed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10 || evt.getKeyCode()==40)
        {
          securityQuestion.requestFocus();
        }
        if(evt.getKeyCode()==38)
        {
          email.requestFocus();
        }
    }//GEN-LAST:event_passwordKeyPressed

    private void securityQuestionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_securityQuestionKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
          answer.requestFocus();
        }
        
    }//GEN-LAST:event_securityQuestionKeyPressed

    private void answerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_answerKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10 || evt.getKeyCode()==40)
        {
          address.requestFocus();
        }
    }//GEN-LAST:event_answerKeyPressed

    private void addressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10 || evt.getKeyCode()==40)
        {
          signUp.requestFocus();
        }
        if(evt.getKeyCode()==38)
        {
          answer.requestFocus();
        }
    }//GEN-LAST:event_addressKeyPressed

    private void closeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_closeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
          this.setVisible(false);
        }
        if(evt.getKeyCode()==38)
        {
          fogotPassword.requestFocus();
        }
    }//GEN-LAST:event_closeKeyPressed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        happyMsg.setVisible(false);
        ok.setVisible(false);
    }//GEN-LAST:event_okActionPerformed

    private void okKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_okKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10)
        {
          happyMsg.setVisible(false);
          ok.setVisible(false);
        }
    }//GEN-LAST:event_okKeyPressed

    private void signUpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signUpKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_signUpKeyReleased

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        // TODO add your handling code here:
        if(!(email.getText().equals("")) && !(email.getText().matches("[a-zA-Z0-9][a-zA-Z0-9_.]*@[A-Za-z0-9]+([.][a-zA-Z]+)+")))
        {
          errorMsg.setText("Invalid Email Address!");
          errorMsg.setVisible(true);
          email.setBackground(new Color(255,51,51));
        }
    }//GEN-LAST:event_emailFocusLost

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        // TODO add your handling code here:
        errorMsg.setVisible(false);
        email.setBackground(new Color(255,255,204));
    }//GEN-LAST:event_emailFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField answer;
    private javax.swing.JButton close;
    private javax.swing.JTextField email;
    private javax.swing.JLabel errorMsg;
    private javax.swing.JButton fogotPassword;
    private javax.swing.JLabel happyMsg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton login;
    private javax.swing.JTextField name;
    private javax.swing.JButton ok;
    private javax.swing.JPasswordField password;
    private javax.swing.JComboBox<String> securityQuestion;
    private javax.swing.JButton signUp;
    // End of variables declaration//GEN-END:variables
}
